# Project information
site_name: TurnipTales Wiki
site_url: https://wiki.turniptales.net/

# Repository
repo_url: https://github.com/TurnipTales/turniptales-wiki
repo_name: turniptales-wiki

extra:
  homepage: https://turniptales.net
  social:
    - icon: material/forum
      link: https://forum.turniptales.net/
      name: Forum
    - icon: fontawesome/brands/discord
      link: https://discord.gg/turniptales

copyright: "Copyright &copy; 2023 - 2024 TurnipTales"

plugins:
  - search:
      lang: de
  - git-revision-date-localized:
      enable_creation_date: true

extra_css:
  - stylesheets/extra.css

extra_javascript: [ 'imprint.js' ]

# configuration
theme:
  name: material
  custom_dir: docs/overrides
  logo: icon.png
  favicon: icon.png
  language: de
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Dark-Mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Light-Mode
  feature:
    tabs: true
  features:
    - navigation.top
    - navigation.footer
    - header.autohide
    - announce.dismiss
    - navigation.sections
    - navigation.indexes
    - toc.follow

# extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      #      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - def_list
  - attr_list
  - tables
  - md_in_html

# page tree
nav:
  - Allgemein:
      - Startseite: index.md
  - Gruppierungen:
      - Allgemein: fraktionen/allgemein.md
      - Staatliche Fraktionen:
          - Stadtverwaltung: fraktionen/stadtverwaltung.md
          - Bundesnachrichtendienst: fraktionen/bundesnachrichtendienst.md
          - Polizei: fraktionen/polizei.md
          - Rettungsdienst: fraktionen/rettungsdienst.md
      - Kriminelle Organisationen:
          - Cali Kartell: ko/calikartell.md
          - Elvetias: ko/elvetias.md
          - La Rose Noire: ko/larosenoire.md
          - Northside Blood Family: ko/northsidebloodfamily.md
          - Pruszków Familie: ko/pruszkowfamilie.md
          - Söldner: ko/söldner.md
  - Commands:
      - Gruppierungen:
          - Fraktionsübergreifend: commands/group/crossfaction.md
          - Stadtverwaltung: commands/group/cityAdministration.md
